# Generated by Django 5.0.6 on 2024-06-06 12:59

import userauths.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover_image',
            field=models.ImageField(blank=True, default='cover.jpg', null=True, upload_to=userauths.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=userauths.models.user_directory_path),
        ),
    ]
