# Generated by Django 5.0.6 on 2024-06-12 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_group_grouppost_page_pagepost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(default='Everyone', max_length=100),
        ),
    ]
